name: 自动部署牛奶管家

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# ✅ 修正后的权限配置
permissions:
  contents: write
  gist: write  # 这是正确的权限名称
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 注入Gist凭据
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: |
        sed -i "s|window.__GIST_TOKEN__ = ''|window.__GIST_TOKEN__ = '$GIST_TOKEN'|g" script.js

    - name: 部署页面
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
